# Generated by Django 5.2.7 on 2025-11-17 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
