# Generated by Django 5.2.7 on 2025-11-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_registration_status_registration_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for participants to register for the event', null=True),
        ),
    ]
