# Generated by Django 5.2.7 on 2025-11-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.institution'),
        ),
    ]
