# Generated by Django 5.2.7 on 2025-11-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
